# Generated by Django 5.0.6 on 2024-06-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
