# Generated by Django 5.0.6 on 2024-06-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_delete_payment"),
        ("users", "0008_subscribe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribe",
            new_name="Subscription",
        ),
    ]
