# Generated by Django 5.0.6 on 2024-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_payment_session_id_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, null=True, verbose_name="ID сессии"),
        ),
    ]
