# Generated by Django 5.0.6 on 2024-06-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_description',
            new_name='lesson_description',
        ),
    ]
