# Generated by Django 5.0.6 on 2024-06-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
